name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branchâ€™s name
  push:
    branches: [source]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

env:
  TEST_THIS: "hello"
  CONTEXT_VAR: ${{ vars.PUBLIC_PAGECLIP_SITE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Show env variables
        run: |
          env
        env:
          SOME_OUTSIDE_VAR: ${{ env.TEST_THIS }}
          OUTSIDE_CONTEXT: ${{ env.CONTEXT_VAR }}
          PUBLIC_RESUME_EMBED_URL: ${{ vars.PUBLIC_RESUME_EMBED_URL }}
          PUBLIC_PAGECLIP_SITE_KEY: ${{ vars.PUBLIC_PAGECLIP_SITE_KEY }}
          PUBLIC_PAGECLIP_FORM_NAME: ${{ vars.PUBLIC_PAGECLIP_FORM_NAME }}
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Install, build, and upload your site
        uses: withastro/action@v1
        with:
          # path: . # The root location of your Astro project inside the repository. (optional)
          node-version: 20
          package-manager: pnpm@latest
        env:
          PUBLIC_RESUME_EMBED_URL: ${{ vars.PUBLIC_PAGECLIP_SITE_KEY }}
          PUBLIC_PAGECLIP_SITE_KEY: ${{ vars.PUBLIC_PAGECLIP_SITE_KEY }}
          PUBLIC_PAGECLIP_FORM_NAME: ${{ vars.PUBLIC_PAGECLIP_FORM_NAME }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
